### ISSUE TITLE
Cannot read properties

### ISSUE THREAD

**Issue by ironicbadger** [estruyf/disqus-to-github-discussions#1]
```
alex@slartibartfast disqus-to-github-discussions % npm start

> migrate-disqus-to-giscus@1.0.0 start
> rm -rf dist && tsc && node dist/index.js

Using PAT access token...

/Users/alex/git/other/disqus-to-github-discussions/dist/utils/getRepositoryId.js:37
    if (response.data.repository.id) {
                      ^

TypeError: Cannot read properties of undefined (reading 'repository')
    at /Users/alex/git/other/disqus-to-github-discussions/dist/utils/getRepositoryId.js:37:23
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alex/git/other/disqus-to-github-discussions/dist/utils/getRepositoryId.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.1.0
```

This is the `.env` file in the same dir as everything else.
```
# GitHub app
APP_ID=""
CLIENT_ID=""
CLIENT_SECRET=""

# GitHub app private key filename
PRIVATE_KEY_FILE=""

# Personal access token
PAT_ACCESS_TOKEN="github_pat_123redacted"

# GitHub repository information
REPOSITORY="blog.ktz.me"
OWNER="ironicbadger"

# Disqus export file
XML_FILE="blogktzme-2022-12-01T23_01_34.997575-all.xml"

# Disqus and site information
DISQUS_USERNAME="ironicbadger"
SITE_URL="blog.ktz.me"

# GitHub category name
CATEGORY_NAME="Announcements"

# Other settings
API_RETRIES="5"
SLEEP_TIME="500"
```

This is for https://github.com/ironicbadger/blog.ktz.me

Did I misconfigure something? Thanks in advance for the tool.

**Comment by estruyf** [comment]
Hi @ironicbadger, I see that your discussions got created. Is this still an issue?

**Comment by ironicbadger** [comment]
Once I manned up and created the GitHub app it was fine. There's some wonky logic somewhere if you don't provide params you don't need. Once I gave it everything it was happy. 

So yes, still valid but I got it working the right way. Might make sense just to ignore the PAT route altogether. 

Thanks for the script. It worked beautifully in the end.

**Comment by estruyf** [comment]
Can you tell me which parameters you had issues with, happy to change some of the logic.

**Comment by ironicbadger** [comment]
See the first comment. Given I got working as an app in the end that's all I can really say.

**Comment by estruyf** [comment]
@ironicbadger which permission scopes did you give to your PAT token?
